### ISSUE TITLE
CT attempted to removeChild with a node that was not a child

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/optics-lab#37]
```
optics-lab : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612502607679/optics-lab/optics-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22optics-lab%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1612502607679%22%2C%22timestamp%22%3A1612504634491%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000
Uncaught Error: Assertion failed: Attempted to removeChild with a node that was not a child.
Error: Assertion failed: Attempted to removeChild with a node that was not a child.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612502607679/assert/js/assert.js:25:13)
at OpticsLabScreenView.removeChild (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612502607679/scenery/js/nodes/Node.js:668:15)
at OpticsLabScreenView.removeComponent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612502607679/optics-lab/js/optics-lab/view/OpticsLabScreenView.js:175:10)
at OpticsLabScreenView.removePiece (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612502607679/optics-lab/js/optics-lab/view/OpticsLabScreenView.js:191:12)
at end (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612502607679/optics-lab/js/optics-lab/view/ToolDrawerPanel.js:73:24)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612502607679/scenery/js/input/SimpleDragHandler.js:237:26
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612502607679/axon/js/Action.js:225:18)
at SimpleDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612502607679/scenery/js/input/SimpleDragHandler.js:360:24)
at Object.up (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612502607679/scenery/js/input/SimpleDragHandler.js:295:16)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612502607679/scenery/js/input/Input.js:1832:25)
id: Bayes Chrome
Snapshot from 2/4/2021, 10:23:27 PM
```

**Comment by pixelzoom** [comment]
In 2/4/21 dev meeting, we established that this may be due to CT multi-touch fuzz testing ( ?fuzzPointers=2) being enabled for phetsims/aqua#106.

**Comment by KatieWoe** [comment]
```
optics-lab : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/optics-lab/optics-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22optics-lab%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647574186761%22%2C%22timestamp%22%3A1647583373245%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Attempted to removeChild with a node that was not a child.
Error: Assertion failed: Attempted to removeChild with a node that was not a child.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/assert/js/assert.js:25:13)
at OpticsLabScreenView.removeChild (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/nodes/Node.js:580:15)
at OpticsLabScreenView.removeComponent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/optics-lab/js/optics-lab/view/OpticsLabScreenView.js:183:10)
at OpticsLabScreenView.removePiece (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/optics-lab/js/optics-lab/view/OpticsLabScreenView.js:200:12)
at end (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/optics-lab/js/optics-lab/view/ToolDrawerPanel.js:66:22)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/input/SimpleDragHandler.js:211:26
at PhetioAction.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/tandem/js/PhetioAction.js:90:17)
at SimpleDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/input/SimpleDragHandler.js:332:24)
at Object.cancel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/input/SimpleDragHandler.js:282:14)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/input/Input.js:1740:23)
id: Bayes Chrome
Snapshot from 3/17/2022, 9:29:46 PM

----------------------------------

optics-lab : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/optics-lab/optics-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22optics-lab%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647574186761%22%2C%22timestamp%22%3A1647582478281%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Attempted to removeChild with a node that was not a child.
Error: Assertion failed: Attempted to removeChild with a node that was not a child.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/assert/js/assert.js:25:13)
at OpticsLabScreenView.removeChild (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/nodes/Node.js:580:15)
at OpticsLabScreenView.removeComponent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/optics-lab/js/optics-lab/view/OpticsLabScreenView.js:183:10)
at OpticsLabScreenView.removePiece (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/optics-lab/js/optics-lab/view/OpticsLabScreenView.js:200:12)
at end (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/optics-lab/js/optics-lab/view/ToolDrawerPanel.js:66:22)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/input/SimpleDragHandler.js:211:26
at PhetioAction.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/tandem/js/PhetioAction.js:90:17)
at SimpleDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/input/SimpleDragHandler.js:332:24)
at Object.up (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/input/SimpleDragHandler.js:264:16)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/scenery/js/input/Input.js:1740:23)
id: Bayes Chrome
Snapshot from 3/17/2022, 9:29:46 PM
```

**Comment by KatieWoe** [comment]
This issue seem to have returned:
```
optics-lab : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652679242118/optics-lab/optics-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22optics-lab%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652679242118%22%2C%22timestamp%22%3A1652692887436%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Attempted to removeChild with a node that was not a child.
Error: Assertion failed: Attempted to removeChild with a node that was not a child.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652679242118/assert/js/assert.js:28:13)
at assert (Node.ts:877:14)
at removeChild (OpticsLabScreenView.js:175:9)
at removeComponent (OpticsLabScreenView.js:191:11)
at removePiece (ToolDrawerPanel.js:73:23)
at call (SimpleDragHandler.js:236:25)
at apply (PhetioAction.ts:123:16)
at execute (SimpleDragHandler.js:364:23)
at endDrag (SimpleDragHandler.js:294:15)
at inputEvent (Input.ts:1825:91)
id: Bayes Chrome
Snapshot from 5/15/2022, 11:34:02 PM
```

**Comment by zepumph** [comment]
Not sure about this one.

**Comment by KatieWoe** [comment]
This issue is still occurring, but no one is assigned. Looking at issues for https://github.com/phetsims/qa/issues/832. @zepumph can you decide what to do with this one?
```
optics-lab : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662738015283/optics-lab/optics-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22optics-lab%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1662738015283%22%2C%22timestamp%22%3A1662744886869%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Attempted to removeChild with a node that was not a child.
Error: Assertion failed: Attempted to removeChild with a node that was not a child.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662738015283/assert/js/assert.js:28:13)
at assert (Node.ts:906:14)
at removeChild (OpticsLabScreenView.js:175:9)
at removeComponent (OpticsLabScreenView.js:191:11)
at removePiece (ToolDrawerPanel.js:68:23)
at call (SimpleDragHandler.js:236:25)
at apply (PhetioAction.ts:124:16)
at execute (SimpleDragHandler.js:364:23)
at endDrag (SimpleDragHandler.js:312:13)
at inputEvent (Input.ts:1804:91)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 9:40:15 AM

----------------------------------

optics-lab : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662738015283/optics-lab/optics-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22optics-lab%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1662738015283%22%2C%22timestamp%22%3A1662758100543%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Attempted to removeChild with a node that was not a child.
Error: Assertion failed: Attempted to removeChild with a node that was not a child.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662738015283/assert/js/assert.js:28:13)
at assert (Node.ts:906:14)
at removeChild (OpticsLabScreenView.js:175:9)
at removeComponent (OpticsLabScreenView.js:191:11)
at removePiece (ToolDrawerPanel.js:68:23)
at call (SimpleDragHandler.js:236:25)
at apply (PhetioAction.ts:124:16)
at execute (SimpleDragHandler.js:364:23)
at endDrag (SimpleDragHandler.js:294:15)
at inputEvent (Input.ts:1804:91)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 9:40:15 AM
```

**Comment by veillette** [comment]
I added a guard in the above commit to prevent such a removal. This is a temporary fix that will merely help to pass CT. I referenced this issue in the codebase for future maintainer(s).

**Comment by veillette** [comment]
The previous commit has appeased CT, but we can leave this issue opened as this is merely a band-aid and a future maintainer should addressed the underlying issue.

**Comment by marlitas** [comment]
It seems this issue may not be fruitful to work on outside of dedicated optics-lab sim time. Marking as `blocks-sim-publication` and `deferred`, although we may want to re-triage if we get through everything else in this CT sprint.
